# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsRefundOnDamageConfig extends Resource

@export var jauge_type: FightingFormsModuleClient.Types.JaugeType 
@export var only_once: bool 
@export var amount: int 
@export var duration: int 

func _init() -> void:
	set_meta('bsatn_type_jauge_type', &'u8')
	set_meta('bsatn_type_only_once', &'bool')
	set_meta('bsatn_type_amount', &'u8')
	set_meta('bsatn_type_duration', &'u8')

## 0. jauge_type: FightingFormsModuleClient.Types.JaugeType[br]
## 1. only_once: bool[br]
## 2. amount: int[br]
## 3. duration: int[br]
static func create(p_jauge_type: FightingFormsModuleClient.Types.JaugeType, p_only_once: bool, p_amount: int, p_duration: int) -> FightingFormsRefundOnDamageConfig:
	var result = FightingFormsRefundOnDamageConfig.new()
	result.jauge_type = p_jauge_type
	result.only_once = p_only_once
	result.amount = p_amount
	result.duration = p_duration
	return result
