# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsCharacterClass extends _ModuleTableType

const module_name := "FightingForms"
const table_names: Array[String] = ['character_class']

@export var id: int 
@export var name: String 
@export var description: String 
@export var hp: int 
@export var mana: int 
@export var stamina: int 
@export var actions_class: Array[FightingFormsModuleClient.Types.ActionClass] 

func _init() -> void:
	set_meta('primary_key', 'id')
	set_meta('bsatn_type_id', &'u16')
	set_meta('bsatn_type_name', &'string')
	set_meta('bsatn_type_description', &'string')
	set_meta('bsatn_type_hp', &'u8')
	set_meta('bsatn_type_mana', &'u8')
	set_meta('bsatn_type_stamina', &'u8')
	set_meta('bsatn_type_actions_class', &'u8')

## 0. id: int[br]
## 1. name: String[br]
## 2. description: String[br]
## 3. hp: int[br]
## 4. mana: int[br]
## 5. stamina: int[br]
## 6. actions_class: Array of FightingFormsModuleClient.Types.ActionClass[br]
static func create(p_id: int, p_name: String, p_description: String, p_hp: int, p_mana: int, p_stamina: int, p_actions_class: Array[FightingFormsModuleClient.Types.ActionClass]) -> FightingFormsCharacterClass:
	var result = FightingFormsCharacterClass.new()
	result.id = p_id
	result.name = p_name
	result.description = p_description
	result.hp = p_hp
	result.mana = p_mana
	result.stamina = p_stamina
	result.actions_class = p_actions_class
	return result
