# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsZytex3Action extends Resource

@export var direction: FightingFormsModuleClient.Types.Direction 

func _init() -> void:
	set_meta('bsatn_type_direction', &'u8')

## 0. direction: FightingFormsModuleClient.Types.Direction[br]
static func create(p_direction: FightingFormsModuleClient.Types.Direction) -> FightingFormsZytex3Action:
	var result = FightingFormsZytex3Action.new()
	result.direction = p_direction
	return result
