# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsCharacter extends _ModuleTableType

const module_name := "FightingForms"
const table_names: Array[String] = ['character']

@export var id: int 
@export var game_id: int 
@export var player_id: PackedByteArray 
@export var character_class_id: int 
@export var choosen_actions: Array[Option] ## Array of Option of FightingFormsAction
@export var current_state: FightingFormsCharacterState 
@export var states: Array[FightingFormsCharacterState] 

func _init() -> void:
	set_meta('primary_key', 'id')
	set_meta('bsatn_type_id', &'u64')
	set_meta('bsatn_type_game_id', &'u64')
	set_meta('bsatn_type_player_id', &'identity')
	set_meta('bsatn_type_character_class_id', &'u16')
	set_meta('bsatn_type_choosen_actions', &'FightingFormsAction')
	set_meta('bsatn_type_current_state', &'FightingFormsCharacterState')
	set_meta('bsatn_type_states', &'FightingFormsCharacterState')

## 0. id: int[br]
## 1. game_id: int[br]
## 2. player_id: PackedByteArray[br]
## 3. character_class_id: int[br]
## 4. choosen_actions: Array of Option of FightingFormsAction[br]
## 5. current_state: FightingFormsCharacterState[br]
## 6. states: Array of FightingFormsCharacterState[br]
static func create(p_id: int, p_game_id: int, p_player_id: PackedByteArray, p_character_class_id: int, p_choosen_actions: Array[Option], p_current_state: FightingFormsCharacterState, p_states: Array[FightingFormsCharacterState]) -> FightingFormsCharacter:
	var result = FightingFormsCharacter.new()
	result.id = p_id
	result.game_id = p_game_id
	result.player_id = p_player_id
	result.character_class_id = p_character_class_id
	result.choosen_actions = p_choosen_actions
	result.current_state = p_current_state
	result.states = p_states
	return result
