# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsCharacterState extends Resource

@export var position: FightingFormsPosition 
@export var hp: int 
@export var mana: int 
@export var stamina: int 
@export var max_hp: int 
@export var max_mana: int 
@export var max_stamina: int 

func _init() -> void:
	set_meta('bsatn_type_position', &'FightingFormsPosition')
	set_meta('bsatn_type_hp', &'u8')
	set_meta('bsatn_type_mana', &'u8')
	set_meta('bsatn_type_stamina', &'u8')
	set_meta('bsatn_type_max_hp', &'u8')
	set_meta('bsatn_type_max_mana', &'u8')
	set_meta('bsatn_type_max_stamina', &'u8')

## 0. position: FightingFormsPosition[br]
## 1. hp: int[br]
## 2. mana: int[br]
## 3. stamina: int[br]
## 4. max_hp: int[br]
## 5. max_mana: int[br]
## 6. max_stamina: int[br]
static func create(p_position: FightingFormsPosition, p_hp: int, p_mana: int, p_stamina: int, p_max_hp: int, p_max_mana: int, p_max_stamina: int) -> FightingFormsCharacterState:
	var result = FightingFormsCharacterState.new()
	result.position = p_position
	result.hp = p_hp
	result.mana = p_mana
	result.stamina = p_stamina
	result.max_hp = p_max_hp
	result.max_mana = p_max_mana
	result.max_stamina = p_max_stamina
	return result
