# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsBardass1Action extends Resource


func _init() -> void:
	pass

static func create() -> FightingFormsBardass1Action:
	var result = FightingFormsBardass1Action.new()
	return result
