# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsApplyStatusConfig extends Resource

@export var character_id: int 
@export var status: FightingFormsStatus 

func _init() -> void:
	set_meta('bsatn_type_character_id', &'u64')
	set_meta('bsatn_type_status', &'FightingFormsStatus')

## 0. character_id: int[br]
## 1. status: FightingFormsStatus[br]
static func create(p_character_id: int, p_status: FightingFormsStatus) -> FightingFormsApplyStatusConfig:
	var result = FightingFormsApplyStatusConfig.new()
	result.character_id = p_character_id
	result.status = p_status
	return result
