# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsStunlor2Action extends Resource

@export var direction: FightingFormsModuleClient.Types.CardinalDirection 

func _init() -> void:
	set_meta('bsatn_type_direction', &'u8')

## 0. direction: FightingFormsModuleClient.Types.CardinalDirection[br]
static func create(p_direction: FightingFormsModuleClient.Types.CardinalDirection) -> FightingFormsStunlor2Action:
	var result = FightingFormsStunlor2Action.new()
	result.direction = p_direction
	return result
