# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsDamageReductionConfig extends Resource

@export var amount: int 
@export var duration: int 
@export var only_once: bool 

func _init() -> void:
	set_meta('bsatn_type_amount', &'u8')
	set_meta('bsatn_type_duration', &'u8')
	set_meta('bsatn_type_only_once', &'bool')

## 0. amount: int[br]
## 1. duration: int[br]
## 2. only_once: bool[br]
static func create(p_amount: int, p_duration: int, p_only_once: bool) -> FightingFormsDamageReductionConfig:
	var result = FightingFormsDamageReductionConfig.new()
	result.amount = p_amount
	result.duration = p_duration
	result.only_once = p_only_once
	return result
