# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsActionClassConfig extends _ModuleTableType

const module_name := "FightingForms"
const table_names: Array[String] = ['action_class_config']

@export var id: int 
@export var action_class: FightingFormsModuleClient.Types.ActionClass 
@export var name: String 
@export var description: String 
@export var mana_cost: int 
@export var stamina_cost: int 
@export var cooldown: int 
@export var duration: int 

func _init() -> void:
	set_meta('primary_key', 'id')
	set_meta('bsatn_type_id', &'u16')
	set_meta('bsatn_type_action_class', &'u8')
	set_meta('bsatn_type_name', &'string')
	set_meta('bsatn_type_description', &'string')
	set_meta('bsatn_type_mana_cost', &'u8')
	set_meta('bsatn_type_stamina_cost', &'u8')
	set_meta('bsatn_type_cooldown', &'u8')
	set_meta('bsatn_type_duration', &'u8')

## 0. id: int[br]
## 1. action_class: FightingFormsModuleClient.Types.ActionClass[br]
## 2. name: String[br]
## 3. description: String[br]
## 4. mana_cost: int[br]
## 5. stamina_cost: int[br]
## 6. cooldown: int[br]
## 7. duration: int[br]
static func create(p_id: int, p_action_class: FightingFormsModuleClient.Types.ActionClass, p_name: String, p_description: String, p_mana_cost: int, p_stamina_cost: int, p_cooldown: int, p_duration: int) -> FightingFormsActionClassConfig:
	var result = FightingFormsActionClassConfig.new()
	result.id = p_id
	result.action_class = p_action_class
	result.name = p_name
	result.description = p_description
	result.mana_cost = p_mana_cost
	result.stamina_cost = p_stamina_cost
	result.cooldown = p_cooldown
	result.duration = p_duration
	return result
