# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsBardass3Action extends Resource


func _init() -> void:
	pass

static func create() -> FightingFormsBardass3Action:
	var result = FightingFormsBardass3Action.new()
	return result
