# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsGame extends _ModuleTableType

const module_name := "FightingForms"
const table_names: Array[String] = ['game']

@export var id: int 
@export var players: Array[PackedByteArray] 
@export var started: bool 
@export var round: int 
@export var ending: bool 

func _init() -> void:
	set_meta('primary_key', 'id')
	set_meta('bsatn_type_id', &'u64')
	set_meta('bsatn_type_players', &'identity')
	set_meta('bsatn_type_started', &'bool')
	set_meta('bsatn_type_round', &'u8')
	set_meta('bsatn_type_ending', &'bool')

## 0. id: int[br]
## 1. players: Array of PackedByteArray[br]
## 2. started: bool[br]
## 3. round: int[br]
## 4. ending: bool[br]
static func create(p_id: int, p_players: Array[PackedByteArray], p_started: bool, p_round: int, p_ending: bool) -> FightingFormsGame:
	var result = FightingFormsGame.new()
	result.id = p_id
	result.players = p_players
	result.started = p_started
	result.round = p_round
	result.ending = p_ending
	return result
