# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsAppliedEffect extends Resource

@export var effect: FightingFormsEffect 
@export var applied: bool 
@export var step: int 

func _init() -> void:
	set_meta('bsatn_type_effect', &'FightingFormsEffect')
	set_meta('bsatn_type_applied', &'bool')
	set_meta('bsatn_type_step', &'u8')

## 0. effect: FightingFormsEffect[br]
## 1. applied: bool[br]
## 2. step: int[br]
static func create(p_effect: FightingFormsEffect, p_applied: bool, p_step: int) -> FightingFormsAppliedEffect:
	var result = FightingFormsAppliedEffect.new()
	result.effect = p_effect
	result.applied = p_applied
	result.step = p_step
	return result
