# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsDamageTileConfig extends Resource

@export var position: FightingFormsPosition 
@export var amount: int 

func _init() -> void:
	set_meta('bsatn_type_position', &'FightingFormsPosition')
	set_meta('bsatn_type_amount', &'u8')

## 0. position: FightingFormsPosition[br]
## 1. amount: int[br]
static func create(p_position: FightingFormsPosition, p_amount: int) -> FightingFormsDamageTileConfig:
	var result = FightingFormsDamageTileConfig.new()
	result.position = p_position
	result.amount = p_amount
	return result
