# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsStunnedConfig extends Resource

@export var duration: int 

func _init() -> void:
	set_meta('bsatn_type_duration', &'u8')

## 0. duration: int[br]
static func create(p_duration: int) -> FightingFormsStunnedConfig:
	var result = FightingFormsStunnedConfig.new()
	result.duration = p_duration
	return result
