# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsRestoreConfig extends Resource

@export var character_id: int 
@export var jauge_type: FightingFormsModuleClient.Types.JaugeType 
@export var amount: int 

func _init() -> void:
	set_meta('bsatn_type_character_id', &'u64')
	set_meta('bsatn_type_jauge_type', &'u8')
	set_meta('bsatn_type_amount', &'u8')

## 0. character_id: int[br]
## 1. jauge_type: FightingFormsModuleClient.Types.JaugeType[br]
## 2. amount: int[br]
static func create(p_character_id: int, p_jauge_type: FightingFormsModuleClient.Types.JaugeType, p_amount: int) -> FightingFormsRestoreConfig:
	var result = FightingFormsRestoreConfig.new()
	result.character_id = p_character_id
	result.jauge_type = p_jauge_type
	result.amount = p_amount
	return result
