# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsTeleportConfig extends Resource

@export var character_id: int 
@export var position: FightingFormsPosition 

func _init() -> void:
	set_meta('bsatn_type_character_id', &'u64')
	set_meta('bsatn_type_position', &'FightingFormsPosition')

## 0. character_id: int[br]
## 1. position: FightingFormsPosition[br]
static func create(p_character_id: int, p_position: FightingFormsPosition) -> FightingFormsTeleportConfig:
	var result = FightingFormsTeleportConfig.new()
	result.character_id = p_character_id
	result.position = p_position
	return result
