# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsMoveConfig extends Resource

@export var character_id: int 
@export var direction: FightingFormsModuleClient.Types.Direction 
@export var distance: int 

func _init() -> void:
	set_meta('bsatn_type_character_id', &'u64')
	set_meta('bsatn_type_direction', &'u8')
	set_meta('bsatn_type_distance', &'u8')

## 0. character_id: int[br]
## 1. direction: FightingFormsModuleClient.Types.Direction[br]
## 2. distance: int[br]
static func create(p_character_id: int, p_direction: FightingFormsModuleClient.Types.Direction, p_distance: int) -> FightingFormsMoveConfig:
	var result = FightingFormsMoveConfig.new()
	result.character_id = p_character_id
	result.direction = p_direction
	result.distance = p_distance
	return result
