# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name FightingFormsEffect extends RustEnum

enum {
	Cost,
	Restore,
	Move,
	Teleport,
	DamageTile,
	StatusTile,
	ApplyStatus,
}

func _init():
	set_meta('enum_options', [&'FightingFormsCostConfig', &'FightingFormsRestoreConfig', &'FightingFormsMoveConfig', &'FightingFormsTeleportConfig', &'FightingFormsDamageTileConfig', &'FightingFormsStatusTileConfig', &'FightingFormsApplyStatusConfig'])
	set_meta('bsatn_enum_type', &'FightingFormsEffect')

static func parse_enum_name(i: int) -> String:
	match i:
		0: return &'Cost'
		1: return &'Restore'
		2: return &'Move'
		3: return &'Teleport'
		4: return &'DamageTile'
		5: return &'StatusTile'
		6: return &'ApplyStatus'
		_:
			printerr("Enum does not have value for %d. This is out of bounds." % i)
			return &'Unknown'

func get_cost() -> FightingFormsCostConfig:
	return data

func get_restore() -> FightingFormsRestoreConfig:
	return data

func get_move() -> FightingFormsMoveConfig:
	return data

func get_teleport() -> FightingFormsTeleportConfig:
	return data

func get_damage_tile() -> FightingFormsDamageTileConfig:
	return data

func get_status_tile() -> FightingFormsStatusTileConfig:
	return data

func get_apply_status() -> FightingFormsApplyStatusConfig:
	return data

static func create(p_type: int, p_data: Variant = null) -> FightingFormsEffect:
	var result = FightingFormsEffect.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_cost(_data: FightingFormsCostConfig) -> FightingFormsEffect:
	return create(Cost, _data)

static func create_restore(_data: FightingFormsRestoreConfig) -> FightingFormsEffect:
	return create(Restore, _data)

static func create_move(_data: FightingFormsMoveConfig) -> FightingFormsEffect:
	return create(Move, _data)

static func create_teleport(_data: FightingFormsTeleportConfig) -> FightingFormsEffect:
	return create(Teleport, _data)

static func create_damage_tile(_data: FightingFormsDamageTileConfig) -> FightingFormsEffect:
	return create(DamageTile, _data)

static func create_status_tile(_data: FightingFormsStatusTileConfig) -> FightingFormsEffect:
	return create(StatusTile, _data)

static func create_apply_status(_data: FightingFormsApplyStatusConfig) -> FightingFormsEffect:
	return create(ApplyStatus, _data)