# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsZytex1Action extends Resource


func _init() -> void:
	pass

static func create() -> FightingFormsZytex1Action:
	var result = FightingFormsZytex1Action.new()
	return result
