# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsStatusTileConfig extends Resource

@export var position: FightingFormsPosition 
@export var status: FightingFormsStatus 

func _init() -> void:
	set_meta('bsatn_type_position', &'FightingFormsPosition')
	set_meta('bsatn_type_status', &'FightingFormsStatus')

## 0. position: FightingFormsPosition[br]
## 1. status: FightingFormsStatus[br]
static func create(p_position: FightingFormsPosition, p_status: FightingFormsStatus) -> FightingFormsStatusTileConfig:
	var result = FightingFormsStatusTileConfig.new()
	result.position = p_position
	result.status = p_status
	return result
