# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name FightingFormsAction extends RustEnum

enum {
	Move,
	Zytex1,
	Zytex2,
	Zytex3,
	Bardass1,
	Bardass2,
	Bardass3,
	Stunlor1,
	Stunlor2,
	Stunlor3,
}

func _init():
	set_meta('enum_options', [&'FightingFormsMoveAction', &'FightingFormsZytex1Action', &'FightingFormsZytex2Action', &'FightingFormsZytex3Action', &'FightingFormsBardass1Action', &'FightingFormsBardass2Action', &'FightingFormsBardass3Action', &'FightingFormsStunlor1Action', &'FightingFormsStunlor2Action', &'FightingFormsStunlor3Action'])
	set_meta('bsatn_enum_type', &'FightingFormsAction')

static func parse_enum_name(i: int) -> String:
	match i:
		0: return &'Move'
		1: return &'Zytex1'
		2: return &'Zytex2'
		3: return &'Zytex3'
		4: return &'Bardass1'
		5: return &'Bardass2'
		6: return &'Bardass3'
		7: return &'Stunlor1'
		8: return &'Stunlor2'
		9: return &'Stunlor3'
		_:
			printerr("Enum does not have value for %d. This is out of bounds." % i)
			return &'Unknown'

func get_move() -> FightingFormsMoveAction:
	return data

func get_zytex_1() -> FightingFormsZytex1Action:
	return data

func get_zytex_2() -> FightingFormsZytex2Action:
	return data

func get_zytex_3() -> FightingFormsZytex3Action:
	return data

func get_bardass_1() -> FightingFormsBardass1Action:
	return data

func get_bardass_2() -> FightingFormsBardass2Action:
	return data

func get_bardass_3() -> FightingFormsBardass3Action:
	return data

func get_stunlor_1() -> FightingFormsStunlor1Action:
	return data

func get_stunlor_2() -> FightingFormsStunlor2Action:
	return data

func get_stunlor_3() -> FightingFormsStunlor3Action:
	return data

static func create(p_type: int, p_data: Variant = null) -> FightingFormsAction:
	var result = FightingFormsAction.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_move(_data: FightingFormsMoveAction) -> FightingFormsAction:
	return create(Move, _data)

static func create_zytex_1(_data: FightingFormsZytex1Action) -> FightingFormsAction:
	return create(Zytex1, _data)

static func create_zytex_2(_data: FightingFormsZytex2Action) -> FightingFormsAction:
	return create(Zytex2, _data)

static func create_zytex_3(_data: FightingFormsZytex3Action) -> FightingFormsAction:
	return create(Zytex3, _data)

static func create_bardass_1(_data: FightingFormsBardass1Action) -> FightingFormsAction:
	return create(Bardass1, _data)

static func create_bardass_2(_data: FightingFormsBardass2Action) -> FightingFormsAction:
	return create(Bardass2, _data)

static func create_bardass_3(_data: FightingFormsBardass3Action) -> FightingFormsAction:
	return create(Bardass3, _data)

static func create_stunlor_1(_data: FightingFormsStunlor1Action) -> FightingFormsAction:
	return create(Stunlor1, _data)

static func create_stunlor_2(_data: FightingFormsStunlor2Action) -> FightingFormsAction:
	return create(Stunlor2, _data)

static func create_stunlor_3(_data: FightingFormsStunlor3Action) -> FightingFormsAction:
	return create(Stunlor3, _data)