# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsPosition extends Resource

@export var x: int 
@export var y: int 

func _init() -> void:
	set_meta('bsatn_type_x', &'u8')
	set_meta('bsatn_type_y', &'u8')

## 0. x: int[br]
## 1. y: int[br]
static func create(p_x: int, p_y: int) -> FightingFormsPosition:
	var result = FightingFormsPosition.new()
	result.x = p_x
	result.y = p_y
	return result
