# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsPlayer extends _ModuleTableType

const module_name := "FightingForms"
const table_names: Array[String] = ['player']

@export var id: PackedByteArray 
@export var name: String 
@export var character_class_id: Option ## Option of int
@export var character_id: Option ## Option of int
@export var connected: bool 
@export var game_id: Option ## Option of int
@export var ready: bool 
@export var eliminated: bool 

func _init() -> void:
	set_meta('primary_key', 'id')
	set_meta('bsatn_type_id', &'identity')
	set_meta('bsatn_type_name', &'string')
	set_meta('bsatn_type_character_class_id', &'u16')
	set_meta('bsatn_type_character_id', &'u64')
	set_meta('bsatn_type_connected', &'bool')
	set_meta('bsatn_type_game_id', &'u64')
	set_meta('bsatn_type_ready', &'bool')
	set_meta('bsatn_type_eliminated', &'bool')

## 0. id: PackedByteArray[br]
## 1. name: String[br]
## 2. character_class_id: Option of int[br]
## 3. character_id: Option of int[br]
## 4. connected: bool[br]
## 5. game_id: Option of int[br]
## 6. ready: bool[br]
## 7. eliminated: bool[br]
static func create(p_id: PackedByteArray, p_name: String, p_character_class_id: Option, p_character_id: Option, p_connected: bool, p_game_id: Option, p_ready: bool, p_eliminated: bool) -> FightingFormsPlayer:
	var result = FightingFormsPlayer.new()
	result.id = p_id
	result.name = p_name
	result.character_class_id = p_character_class_id
	result.character_id = p_character_id
	result.connected = p_connected
	result.game_id = p_game_id
	result.ready = p_ready
	result.eliminated = p_eliminated
	return result
