# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name FightingFormsStatus extends RustEnum

enum {
	Stunned,
	DamageReduction,
	RefundOnDamage,
}

func _init():
	set_meta('enum_options', [&'FightingFormsStunnedConfig', &'FightingFormsDamageReductionConfig', &'FightingFormsRefundOnDamageConfig'])
	set_meta('bsatn_enum_type', &'FightingFormsStatus')

static func parse_enum_name(i: int) -> String:
	match i:
		0: return &'Stunned'
		1: return &'DamageReduction'
		2: return &'RefundOnDamage'
		_:
			printerr("Enum does not have value for %d. This is out of bounds." % i)
			return &'Unknown'

func get_stunned() -> FightingFormsStunnedConfig:
	return data

func get_damage_reduction() -> FightingFormsDamageReductionConfig:
	return data

func get_refund_on_damage() -> FightingFormsRefundOnDamageConfig:
	return data

static func create(p_type: int, p_data: Variant = null) -> FightingFormsStatus:
	var result = FightingFormsStatus.new()
	result.value = p_type
	result.data = p_data
	return result

static func create_stunned(_data: FightingFormsStunnedConfig) -> FightingFormsStatus:
	return create(Stunned, _data)

static func create_damage_reduction(_data: FightingFormsDamageReductionConfig) -> FightingFormsStatus:
	return create(DamageReduction, _data)

static func create_refund_on_damage(_data: FightingFormsRefundOnDamageConfig) -> FightingFormsStatus:
	return create(RefundOnDamage, _data)