# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name FightingFormsModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## 0. action: Option of FightingFormsAction [br]
## 1. step: int [br]
func choose_action(action: Option, step: int, cb: Callable = func(_t: TransactionUpdateMessage): pass) -> Error:
	var __handle__ := _client.call_reducer('choose_action', [action, step], [&'FightingFormsAction', &'u8'])
	if __handle__.error: return __handle__.error
	var __result__ = await __handle__.wait_for_response()
	cb.call(__result__)
	return OK


func create_game(cb: Callable = func(_t: TransactionUpdateMessage): pass) -> Error:
	var __handle__ := _client.call_reducer('create_game', [], [])
	if __handle__.error: return __handle__.error
	var __result__ = await __handle__.wait_for_response()
	cb.call(__result__)
	return OK

## 0. is_ready: bool [br]
func ready(is_ready: bool, cb: Callable = func(_t: TransactionUpdateMessage): pass) -> Error:
	var __handle__ := _client.call_reducer('ready', [is_ready], [&'bool'])
	if __handle__.error: return __handle__.error
	var __result__ = await __handle__.wait_for_response()
	cb.call(__result__)
	return OK

## 0. character_class_id: int [br]
func select_character_class(character_class_id: int, cb: Callable = func(_t: TransactionUpdateMessage): pass) -> Error:
	var __handle__ := _client.call_reducer('select_character_class', [character_class_id], [&'u16'])
	if __handle__.error: return __handle__.error
	var __result__ = await __handle__.wait_for_response()
	cb.call(__result__)
	return OK

## 0. game_id: int [br]
func select_game(game_id: int, cb: Callable = func(_t: TransactionUpdateMessage): pass) -> Error:
	var __handle__ := _client.call_reducer('select_game', [game_id], [&'u64'])
	if __handle__.error: return __handle__.error
	var __result__ = await __handle__.wait_for_response()
	cb.call(__result__)
	return OK

## 0. name: String [br]
func set_name(name: String, cb: Callable = func(_t: TransactionUpdateMessage): pass) -> Error:
	var __handle__ := _client.call_reducer('set_name', [name], [&'string'])
	if __handle__.error: return __handle__.error
	var __result__ = await __handle__.wait_for_response()
	cb.call(__result__)
	return OK