# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

const ActionClassConfig = preload('res://spacetime_bindings/schema/types/fighting_forms_action_class_config.gd')
enum ActionClass {
	Move,
	Zytex1,
	Zytex2,
	Zytex3,
	Bardass1,
	Bardass2,
	Bardass3,
	Stunlor1,
	Stunlor2,
	Stunlor3
}
const Character = preload('res://spacetime_bindings/schema/types/fighting_forms_character.gd')
const Action = preload('res://spacetime_bindings/schema/types/fighting_forms_action.gd')
const MoveAction = preload('res://spacetime_bindings/schema/types/fighting_forms_move_action.gd')
enum Direction {
	North,
	NorthEast,
	East,
	SouthEast,
	South,
	SouthWest,
	West,
	NorthWest
}
const Zytex1Action = preload('res://spacetime_bindings/schema/types/fighting_forms_zytex_1_action.gd')
const Zytex2Action = preload('res://spacetime_bindings/schema/types/fighting_forms_zytex_2_action.gd')
const Zytex3Action = preload('res://spacetime_bindings/schema/types/fighting_forms_zytex_3_action.gd')
const Bardass1Action = preload('res://spacetime_bindings/schema/types/fighting_forms_bardass_1_action.gd')
const Bardass2Action = preload('res://spacetime_bindings/schema/types/fighting_forms_bardass_2_action.gd')
enum CardinalDirection {
	North,
	East,
	South,
	West
}
const Bardass3Action = preload('res://spacetime_bindings/schema/types/fighting_forms_bardass_3_action.gd')
const Stunlor1Action = preload('res://spacetime_bindings/schema/types/fighting_forms_stunlor_1_action.gd')
const Stunlor2Action = preload('res://spacetime_bindings/schema/types/fighting_forms_stunlor_2_action.gd')
const Stunlor3Action = preload('res://spacetime_bindings/schema/types/fighting_forms_stunlor_3_action.gd')
const CharacterState = preload('res://spacetime_bindings/schema/types/fighting_forms_character_state.gd')
const Position = preload('res://spacetime_bindings/schema/types/fighting_forms_position.gd')
const Status = preload('res://spacetime_bindings/schema/types/fighting_forms_status.gd')
const StunnedConfig = preload('res://spacetime_bindings/schema/types/fighting_forms_stunned_config.gd')
const DamageReductionConfig = preload('res://spacetime_bindings/schema/types/fighting_forms_damage_reduction_config.gd')
const RefundOnDamageConfig = preload('res://spacetime_bindings/schema/types/fighting_forms_refund_on_damage_config.gd')
enum JaugeType {
	Hp,
	Mana,
	Stamina
}
const CharacterClass = preload('res://spacetime_bindings/schema/types/fighting_forms_character_class.gd')
const Game = preload('res://spacetime_bindings/schema/types/fighting_forms_game.gd')
const AppliedEffect = preload('res://spacetime_bindings/schema/types/fighting_forms_applied_effect.gd')
const Effect = preload('res://spacetime_bindings/schema/types/fighting_forms_effect.gd')
const CostConfig = preload('res://spacetime_bindings/schema/types/fighting_forms_cost_config.gd')
const RestoreConfig = preload('res://spacetime_bindings/schema/types/fighting_forms_restore_config.gd')
const MoveConfig = preload('res://spacetime_bindings/schema/types/fighting_forms_move_config.gd')
const TeleportConfig = preload('res://spacetime_bindings/schema/types/fighting_forms_teleport_config.gd')
const DamageTileConfig = preload('res://spacetime_bindings/schema/types/fighting_forms_damage_tile_config.gd')
const StatusTileConfig = preload('res://spacetime_bindings/schema/types/fighting_forms_status_tile_config.gd')
const ApplyStatusConfig = preload('res://spacetime_bindings/schema/types/fighting_forms_apply_status_config.gd')
const Player = preload('res://spacetime_bindings/schema/types/fighting_forms_player.gd')
