# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name FightingFormsModuleClient extends SpacetimeDBClient

const Types = preload('res://spacetime_bindings/schema/module_fighting_forms_types.gd')

const ActionClassConfig = Types.ActionClassConfig
const ActionClass = Types.ActionClass
const Character = Types.Character
const Action = Types.Action
const MoveAction = Types.MoveAction
const Direction = Types.Direction
const Zytex1Action = Types.Zytex1Action
const Zytex2Action = Types.Zytex2Action
const Zytex3Action = Types.Zytex3Action
const Bardass1Action = Types.Bardass1Action
const Bardass2Action = Types.Bardass2Action
const CardinalDirection = Types.CardinalDirection
const Bardass3Action = Types.Bardass3Action
const Stunlor1Action = Types.Stunlor1Action
const Stunlor2Action = Types.Stunlor2Action
const Stunlor3Action = Types.Stunlor3Action
const CharacterState = Types.CharacterState
const Position = Types.Position
const Status = Types.Status
const StunnedConfig = Types.StunnedConfig
const DamageReductionConfig = Types.DamageReductionConfig
const RefundOnDamageConfig = Types.RefundOnDamageConfig
const JaugeType = Types.JaugeType
const CharacterClass = Types.CharacterClass
const Game = Types.Game
const AppliedEffect = Types.AppliedEffect
const Effect = Types.Effect
const CostConfig = Types.CostConfig
const RestoreConfig = Types.RestoreConfig
const MoveConfig = Types.MoveConfig
const TeleportConfig = Types.TeleportConfig
const DamageTileConfig = Types.DamageTileConfig
const StatusTileConfig = Types.StatusTileConfig
const ApplyStatusConfig = Types.ApplyStatusConfig
const Player = Types.Player

var reducers: FightingFormsModuleReducers
var db: FightingFormsModuleDb

func _init() -> void:
	set_meta("module_name", "FightingForms")
	name = "FightingFormsModule"
	reducers = preload('res://spacetime_bindings/schema/module_fighting_forms_reducers.gd').new(self)

func _init_db(p_local_db: LocalDatabase) -> void:
	db = preload('res://spacetime_bindings/schema/module_fighting_forms_db.gd').new(p_local_db)
