# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name FightingFormsModuleDb extends RefCounted

const table_names := ["action_class_config", "character", "character_class", "game", "player"]

var action_class_config: FightingFormsActionClassConfigTable
var character: FightingFormsCharacterTable
var character_class: FightingFormsCharacterClassTable
var game: FightingFormsGameTable
var player: FightingFormsPlayerTable

func _init(p_local_db: LocalDatabase) -> void:
	action_class_config = preload('res://spacetime_bindings/schema/tables/fighting_forms_action_class_config_table.gd').new(p_local_db)
	character = preload('res://spacetime_bindings/schema/tables/fighting_forms_character_table.gd').new(p_local_db)
	character_class = preload('res://spacetime_bindings/schema/tables/fighting_forms_character_class_table.gd').new(p_local_db)
	game = preload('res://spacetime_bindings/schema/tables/fighting_forms_game_table.gd').new(p_local_db)
	player = preload('res://spacetime_bindings/schema/tables/fighting_forms_player_table.gd').new(p_local_db)
