# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name SpacetimeAutoload extends Node

var FightingForms: FightingFormsModuleClient

func _init() -> void:
	FightingForms = preload('res://spacetime_bindings/schema/module_fighting_forms_client.gd').new()
	add_child(FightingForms)
