# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name FightingFormsPlayerTable extends _ModuleTable

var id: FightingFormsPlayerIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	set_meta("table_name", "player")
	id = FightingFormsPlayerIdUniqueIndex.new(p_local_db)

func iter() -> Array[FightingFormsPlayer]:
	var rows: Array = super()
	var typed_array: Array[FightingFormsPlayer] = []
	typed_array.assign(rows)
	return typed_array
