# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name FightingFormsActionClassConfigTable extends _ModuleTable

var action_class: FightingFormsActionClassConfigActionClassUniqueIndex
var id: FightingFormsActionClassConfigIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	set_meta("table_name", "action_class_config")
	action_class = FightingFormsActionClassConfigActionClassUniqueIndex.new(p_local_db)
	id = FightingFormsActionClassConfigIdUniqueIndex.new(p_local_db)

func iter() -> Array[FightingFormsActionClassConfig]:
	var rows: Array = super()
	var typed_array: Array[FightingFormsActionClassConfig] = []
	typed_array.assign(rows)
	return typed_array
