# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name FightingFormsActionClassConfigActionClassUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[FightingFormsModuleClient.Types.ActionClass, FightingFormsActionClassConfig] = {}

func _init(p_local_db: LocalDatabase) -> void:
	set_meta("table_name", "action_class_config")
	set_meta("field_name", "action_class")
	_connect_cache_to_db(_cache, p_local_db)

func find(col_val: FightingFormsModuleClient.Types.ActionClass) -> FightingFormsActionClassConfig:
	return _cache.get(col_val, null)
