# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name FightingFormsCharacterClassTable extends _ModuleTable

var id: FightingFormsCharacterClassIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	set_meta("table_name", "character_class")
	id = FightingFormsCharacterClassIdUniqueIndex.new(p_local_db)

func iter() -> Array[FightingFormsCharacterClass]:
	var rows: Array = super()
	var typed_array: Array[FightingFormsCharacterClass] = []
	typed_array.assign(rows)
	return typed_array
